///////////////////////////////////////////////////////////////////////////////
// (c) Copyright 2008 Xilinx, Inc. All rights reserved.
//
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
//
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.
// 
// 
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 7.1i
//  \   \         Application : 
//  /   /         Filename : aur1_GTP_WRAPPER.v
// /___/   /\     Timestamp : 02/08/2005 09:12:43
// \   \  /  \ 
//  \___\/\___\ 
//
////////////////////////////////////////////////////////////////////////////////
//Command: 
//Design Name: aur1_GTP_WRAPPER
//
// Module aur1_GTP_WRAPPER
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
////////////////////////////////////////////////////////////////////////////////
`timescale 1ns / 1ps
(* core_generation_info = "aur1,aurora_8b10b_v5_1,{backchannel_mode=Sidebands, c_aurora_lanes=4, c_column_used=left, c_gt_clock_1=GTPD7, c_gt_clock_2=None, c_gt_loc_1=X, c_gt_loc_10=X, c_gt_loc_11=X, c_gt_loc_12=X, c_gt_loc_13=3, c_gt_loc_14=4, c_gt_loc_15=1, c_gt_loc_16=2, c_gt_loc_17=X, c_gt_loc_18=X, c_gt_loc_19=X, c_gt_loc_2=X, c_gt_loc_20=X, c_gt_loc_21=X, c_gt_loc_22=X, c_gt_loc_23=X, c_gt_loc_24=X, c_gt_loc_25=X, c_gt_loc_26=X, c_gt_loc_27=X, c_gt_loc_28=X, c_gt_loc_29=X, c_gt_loc_3=X, c_gt_loc_30=X, c_gt_loc_31=X, c_gt_loc_32=X, c_gt_loc_33=X, c_gt_loc_34=X, c_gt_loc_35=X, c_gt_loc_36=X, c_gt_loc_37=X, c_gt_loc_38=X, c_gt_loc_39=X, c_gt_loc_4=X, c_gt_loc_40=X, c_gt_loc_41=X, c_gt_loc_42=X, c_gt_loc_43=X, c_gt_loc_44=X, c_gt_loc_45=X, c_gt_loc_46=X, c_gt_loc_47=X, c_gt_loc_48=X, c_gt_loc_5=X, c_gt_loc_6=X, c_gt_loc_7=X, c_gt_loc_8=X, c_gt_loc_9=X, c_lane_width=2, c_line_rate=3.125, c_nfc=false, c_nfc_mode=IMM, c_refclk_frequency=156.25, c_simplex=false, c_simplex_mode=TX, c_stream=true, c_ufc=false, flow_mode=None, interface_mode=Streaming, dataflow_config=Duplex,}" *)
module aur1_GTP_WRAPPER #
(
    // Simulation attributes
    parameter   SIM_MODE              =   "FAST",  // Set to Fast Functional Simulation Model
    parameter   SIM_GTPRESET_SPEEDUP=   0,      // Set to 1 to speed up sim reset
    parameter   SIM_PLL_PERDIV2     =   9'h140,    // Set to the VCO Unit Interval time

    parameter  CHAN_BOND_LEVEL_0 = 3'h0,
    parameter  CHAN_BOND_LEVEL_1 = 3'h0,

    // Channel bond MASTER/SLAVE connection
    parameter CHAN_BOND_MODE_0 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE1 = "MASTER",
    parameter CHAN_BOND_MODE_0_LANE2 = "SLAVE",
    parameter CHAN_BOND_MODE_0_LANE3 = "SLAVE",
    
    parameter CHAN_BOND_MODE_1 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE1 = "MASTER",
    parameter CHAN_BOND_MODE_1_LANE2 = "SLAVE",
    parameter CHAN_BOND_MODE_1_LANE3 = "SLAVE",
    // Refclk attributes
    parameter   CLKINDC_B           =   "TRUE"
)
(
   RESETDONE, //Fix for CR519148
   RESET_LISM,

//---------------------- Loopback and Powerdown Ports ----------------------
   LOOPBACK_IN,
//--------------------- Receive Ports - 8b10b Decoder ----------------------
    RXCHARISCOMMA_OUT,
    RXCHARISCOMMA_OUT_LANE1,
    RXCHARISCOMMA_OUT_LANE2,
    RXCHARISCOMMA_OUT_LANE3,
    RXCHARISK_OUT,
    RXCHARISK_OUT_LANE1,
    RXCHARISK_OUT_LANE2,
    RXCHARISK_OUT_LANE3,
    RXDISPERR_OUT,
    RXDISPERR_OUT_LANE1,
    RXDISPERR_OUT_LANE2,
    RXDISPERR_OUT_LANE3,
    RXNOTINTABLE_OUT,
    RXNOTINTABLE_OUT_LANE1,
    RXNOTINTABLE_OUT_LANE2,
    RXNOTINTABLE_OUT_LANE3,
//----------------- Receive Ports - Channel Bonding Ports -----------------
    ENCHANSYNC_IN,
    ENCHANSYNC_IN_LANE1,
    ENCHANSYNC_IN_LANE2,
    ENCHANSYNC_IN_LANE3,
    CHBONDDONE_OUT,
    CHBONDDONE_OUT_LANE1,
    CHBONDDONE_OUT_LANE2,
    CHBONDDONE_OUT_LANE3,
//----------------- Receive Ports - Clock Correction Ports -----------------
    RXBUFERR_OUT,
    RXBUFERR_OUT_LANE1,
    RXBUFERR_OUT_LANE2,
    RXBUFERR_OUT_LANE3,
//------------- Receive Ports - Comma Detection and Alignment --------------
    RXREALIGN_OUT,
    RXREALIGN_OUT_LANE1,
    RXREALIGN_OUT_LANE2,
    RXREALIGN_OUT_LANE3,
    ENMCOMMAALIGN_IN,
    ENMCOMMAALIGN_IN_LANE1,
    ENMCOMMAALIGN_IN_LANE2,
    ENMCOMMAALIGN_IN_LANE3,
    ENPCOMMAALIGN_IN,
    ENPCOMMAALIGN_IN_LANE1,
    ENPCOMMAALIGN_IN_LANE2,
    ENPCOMMAALIGN_IN_LANE3,
//----------------- Receive Ports - RX Data Path interface -----------------
    RXDATA_OUT,
    RXDATA_OUT_LANE1,
    RXDATA_OUT_LANE2,
    RXDATA_OUT_LANE3,
    RXRECCLK1_OUT,
    RXRECCLK1_OUT_LANE1,
    RXRECCLK1_OUT_LANE2,
    RXRECCLK1_OUT_LANE3,
    RXRECCLK2_OUT,
    RXRECCLK2_OUT_LANE1,
    RXRECCLK2_OUT_LANE2,
    RXRECCLK2_OUT_LANE3,
    RXRESET_IN,
    RXRESET_IN_LANE1,
    RXRESET_IN_LANE2,
    RXRESET_IN_LANE3,
    RXUSRCLK_IN,
    RXUSRCLK2_IN,
//----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    RX1N_IN,
    RX1N_IN_LANE1,
    RX1N_IN_LANE2,
    RX1N_IN_LANE3,
    RX1P_IN,
    RX1P_IN_LANE1,
    RX1P_IN_LANE2,
    RX1P_IN_LANE3,
//--------------- Receive Ports - RX Polarity Control Ports ----------------
    RXPOLARITY_IN,
    RXPOLARITY_IN_LANE1,
    RXPOLARITY_IN_LANE2,
    RXPOLARITY_IN_LANE3,
//------------------- Shared Ports - Tile and PLL Ports --------------------
    REFCLK,
    GTPRESET_IN,
    PLLLKDET_OUT,
    PLLLKDET_OUT_LANE1,
    REFCLKOUT_OUT,
    REFCLKOUT_OUT_LANE1,
//-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    TXCHARISK_IN,
    TXCHARISK_IN_LANE1,
    TXCHARISK_IN_LANE2,
    TXCHARISK_IN_LANE3,
//---------------- Transmit Ports - TX Data Path interface -----------------
    TXDATA_IN,
    TXDATA_IN_LANE1,
    TXDATA_IN_LANE2,
    TXDATA_IN_LANE3,
    TXOUTCLK1_OUT,
    TXOUTCLK1_OUT_LANE1,
    TXOUTCLK1_OUT_LANE2,
    TXOUTCLK1_OUT_LANE3,
    TXOUTCLK2_OUT,
    TXOUTCLK2_OUT_LANE1,
    TXOUTCLK2_OUT_LANE2,
    TXOUTCLK2_OUT_LANE3,
    TXRESET_IN,
    TXRESET_IN_LANE1,
    TXRESET_IN_LANE2,
    TXRESET_IN_LANE3,
    TXUSRCLK_IN,
    TXUSRCLK2_IN,
    TXBUFERR_OUT,
    TXBUFERR_OUT_LANE1,
    TXBUFERR_OUT_LANE2,
    TXBUFERR_OUT_LANE3,
//------------- Transmit Ports - TX Driver and OOB signalling --------------
    TX1N_OUT,
    TX1N_OUT_LANE1,
    TX1N_OUT_LANE2,
    TX1N_OUT_LANE3,
    TX1P_OUT,
    TX1P_OUT_LANE1,
    TX1P_OUT_LANE2,
    TX1P_OUT_LANE3,
	
	TXPREEMP,
	TXDIFF,
 


 



    POWERDOWN_IN
);
//***************************** Port Declarations *****************************
output              RESETDONE; //Fix for CR519148
output              RESET_LISM;
//---------------------- Loopback and Powerdown Ports ----------------------
 input    [2:0]    LOOPBACK_IN;
//--------------------- Receive Ports - 8b10b Decoder ----------------------
 output   [1:0]    RXCHARISCOMMA_OUT; 
 output   [1:0]    RXCHARISK_OUT; 
 output   [1:0]    RXDISPERR_OUT;
 output   [1:0]    RXNOTINTABLE_OUT;
 output   [1:0]    RXCHARISCOMMA_OUT_LANE1; 
 output   [1:0]    RXCHARISK_OUT_LANE1; 
 output   [1:0]    RXDISPERR_OUT_LANE1;
 output   [1:0]    RXNOTINTABLE_OUT_LANE1;
 output   [1:0]    RXCHARISCOMMA_OUT_LANE2; 
 output   [1:0]    RXCHARISK_OUT_LANE2; 
 output   [1:0]    RXDISPERR_OUT_LANE2;
 output   [1:0]    RXNOTINTABLE_OUT_LANE2;
 output   [1:0]    RXCHARISCOMMA_OUT_LANE3; 
 output   [1:0]    RXCHARISK_OUT_LANE3; 
 output   [1:0]    RXDISPERR_OUT_LANE3;
 output   [1:0]    RXNOTINTABLE_OUT_LANE3;
//----------------- Receive Ports - Channel Bonding Ports -----------------
 
 input             ENCHANSYNC_IN; 
 output            CHBONDDONE_OUT;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT;
 input             ENMCOMMAALIGN_IN;
 input             ENPCOMMAALIGN_IN;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [15:0]   RXDATA_OUT; 
 output            RXRECCLK1_OUT;
 output            RXRECCLK2_OUT;
 input             RXRESET_IN;
  
 input             ENCHANSYNC_IN_LANE1; 
 output            CHBONDDONE_OUT_LANE1;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE1;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE1;
 input             ENMCOMMAALIGN_IN_LANE1;
 input             ENPCOMMAALIGN_IN_LANE1;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [15:0]   RXDATA_OUT_LANE1; 
 output            RXRECCLK1_OUT_LANE1;
 output            RXRECCLK2_OUT_LANE1;
 input             RXRESET_IN_LANE1;
  
 input             ENCHANSYNC_IN_LANE2; 
 output            CHBONDDONE_OUT_LANE2;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE2;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE2;
 input             ENMCOMMAALIGN_IN_LANE2;
 input             ENPCOMMAALIGN_IN_LANE2;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [15:0]   RXDATA_OUT_LANE2; 
 output            RXRECCLK1_OUT_LANE2;
 output            RXRECCLK2_OUT_LANE2;
 input             RXRESET_IN_LANE2;
  
 input             ENCHANSYNC_IN_LANE3; 
 output            CHBONDDONE_OUT_LANE3;
//----------------- Receive Ports - Clock Correction Ports -----------------
 output            RXBUFERR_OUT_LANE3;
//------------- Receive Ports - Comma Detection and Alignment --------------
 output            RXREALIGN_OUT_LANE3;
 input             ENMCOMMAALIGN_IN_LANE3;
 input             ENPCOMMAALIGN_IN_LANE3;
//----------------- Receive Ports - RX Data Path interface -----------------
 output   [15:0]   RXDATA_OUT_LANE3; 
 output            RXRECCLK1_OUT_LANE3;
 output            RXRECCLK2_OUT_LANE3;
 input             RXRESET_IN_LANE3;
  input             RXUSRCLK_IN;
 input             RXUSRCLK2_IN;
//----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
 
 input             RX1N_IN;  
 input             RX1P_IN;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN;
 
 input             RX1N_IN_LANE1;  
 input             RX1P_IN_LANE1;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE1;
 
 input             RX1N_IN_LANE2;  
 input             RX1P_IN_LANE2;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE2;
 
 input             RX1N_IN_LANE3;  
 input             RX1P_IN_LANE3;  
//--------------- Receive Ports - RX Polarity Control Ports ----------------
 input             RXPOLARITY_IN_LANE3;
//------------------- Shared Ports - Tile and PLL Ports --------------------
 input             REFCLK;
 input             GTPRESET_IN;
 output            PLLLKDET_OUT;
 output            PLLLKDET_OUT_LANE1;
 input             POWERDOWN_IN;
 output            REFCLKOUT_OUT;
 output            REFCLKOUT_OUT_LANE1;
//-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
 input    [1:0]    TXCHARISK_IN; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [15:0]   TXDATA_IN; 
 output            TXOUTCLK1_OUT;
 output            TXOUTCLK2_OUT;
 input             TXRESET_IN;
 output            TXBUFERR_OUT;
 input    [1:0]    TXCHARISK_IN_LANE1; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [15:0]   TXDATA_IN_LANE1; 
 output            TXOUTCLK1_OUT_LANE1;
 output            TXOUTCLK2_OUT_LANE1;
 input             TXRESET_IN_LANE1;
 output            TXBUFERR_OUT_LANE1;
 input    [1:0]    TXCHARISK_IN_LANE2; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [15:0]   TXDATA_IN_LANE2; 
 output            TXOUTCLK1_OUT_LANE2;
 output            TXOUTCLK2_OUT_LANE2;
 input             TXRESET_IN_LANE2;
 output            TXBUFERR_OUT_LANE2;
 input    [1:0]    TXCHARISK_IN_LANE3; 
//---------------- Transmit Ports - TX Data Path interface -----------------
 input    [15:0]   TXDATA_IN_LANE3; 
 output            TXOUTCLK1_OUT_LANE3;
 output            TXOUTCLK2_OUT_LANE3;
 input             TXRESET_IN_LANE3;
 output            TXBUFERR_OUT_LANE3;
 input             TXUSRCLK_IN;
 input             TXUSRCLK2_IN;
//------------- Transmit Ports - TX Driver and OOB signalling --------------
 output            TX1N_OUT;
 output            TX1P_OUT;
 output            TX1N_OUT_LANE1;
 output            TX1P_OUT_LANE1;
 output            TX1N_OUT_LANE2;
 output            TX1P_OUT_LANE2;
 output            TX1N_OUT_LANE3;
 output            TX1P_OUT_LANE3;

 input	[2:0]		TXDIFF;
 input	[2:0]		TXPREEMP;



 




//***************************** Wire Declarations *****************************
// Ground and VCC signals
 wire               tied_to_ground_i;
 wire    [63:0]     tied_to_ground_vec_i;
 wire               tied_to_vcc_i;
 wire    [63:0]     tied_to_vcc_vec_i;
// floating input port connection signals
 wire     [1:0]    open_rxbufstatus_i;
 wire              open_txbufstatus_i;
 wire     [1:0]    open_rxbufstatus_lane1_i;
 wire              open_txbufstatus_lane1_i;
 wire     [1:0]    open_rxbufstatus_lane2_i;
 wire              open_txbufstatus_lane2_i;
 wire     [1:0]    open_rxbufstatus_lane3_i;
 wire              open_txbufstatus_lane3_i;


// wire to output lock signal
 wire              plllkdet_i;
 wire              plllkdet_lane1_i;

// Electrical idle reset logic signals
 wire               rxenelecidleresetb_i;
 wire               rxelecidle0_i;
 wire               resetdone0_i;
 wire               rxelecidlereset0_i;
 wire               rxelecidle1_i;
 wire               resetdone1_i;
 wire               rxelecidlereset1_i;
 wire               rxenelecidleresetb_lane1_i;
 wire               rxelecidle0_lane1_i;
 wire               resetdone0_lane1_i;
 wire               rxelecidlereset0_lane1_i;
 wire               rxelecidle1_lane1_i;
 wire               resetdone1_lane1_i;
 wire               rxelecidlereset1_lane1_i;
// Channel Bonding 3
 wire     [2:0]    chbondi;
 wire     [2:0]    chbondo;
 wire     [2:0]    chbondi_LANE1;
 wire     [2:0]    chbondo_LANE1;
 wire     [2:0]    chbondi_LANE2;
 wire     [2:0]    chbondo_LANE2;
 wire     [2:0]    chbondi_LANE3;
 wire     [2:0]    chbondo_LANE3;
 wire     [2:0]    chbondi_unused_i;

//********************************* Main Body of Code**************************
//-------------------------  Static signal Assigments ---------------------   
 assign tied_to_ground_i             = 1'b0;
 assign tied_to_ground_vec_i         = 64'h0000000000000000;
 assign tied_to_vcc_i                = 1'b1;
 assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;

// Assign lock signals
 assign  PLLLKDET_OUT  =   plllkdet_i;
 assign  PLLLKDET_OUT_LANE1  =   plllkdet_lane1_i;


 assign serialloopback_i   = !LOOPBACK_IN[0] && LOOPBACK_IN[1] && !LOOPBACK_IN[2];

assign RESETDONE = resetdone0_i || resetdone1_i   || resetdone0_lane1_i || resetdone1_lane1_i ; //Fix for CR519148
assign RESET_LISM = rxelecidlereset0_i || rxelecidlereset1_i  || rxelecidlereset0_lane1_i ||  rxelecidlereset1_lane1_i ;

//-------------------------  Electrical Idle Reset Circuit  ---------------
//Drive RXELECIDLERESET with elec idle reset enabled during normal operation when RXELECIDLE goes high
 assign  rxelecidlereset0_i = (rxelecidle0_i && resetdone0_i) && !serialloopback_i;
 assign  rxelecidlereset1_i = (rxelecidle1_i && resetdone1_i) && !serialloopback_i;
 assign  rxenelecidleresetb_i = !(rxelecidlereset0_i||rxelecidlereset1_i); 
//-------------------------  Electrical Idle Reset Circuit  ---------------
//Drive RXELECIDLERESET with elec idle reset enabled during normal operation when RXELECIDLE goes high
 assign  rxelecidlereset0_lane1_i = (rxelecidle0_lane1_i && resetdone0_lane1_i) && !serialloopback_i;
 assign  rxelecidlereset1_lane1_i = (rxelecidle1_lane1_i && resetdone1_lane1_i) && !serialloopback_i;
 assign  rxenelecidleresetb_lane1_i = !(rxelecidlereset0_lane1_i||rxelecidlereset1_lane1_i); 

// Channel Bonding
 assign chbondi_unused_i  = 3'b000;

 assign  chbondi = chbondo_LANE1;
 assign  chbondi_LANE1 = chbondi_unused_i;
 assign  chbondi_LANE2 = chbondo_LANE1;
 assign  chbondi_LANE3 = chbondo_LANE2;

//------------------------- GTX/GTP Instantiations  --------------------------   
 



   
//*************************************************************************************************            
//-----------------------------------Both GTPs in a Tile-------------------------------------------
//*************************************************************************************************
aur1_GTP_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTPRESET_SPEEDUP     (SIM_GTPRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (3'h1),
        .TILE_CHAN_BOND_LEVEL_1            (3'h2),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE1)
     ) 
GTP_TILE_INST (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         .RXPOWERDOWN0_IN                ({POWERDOWN_IN,POWERDOWN_IN}),
         .RXPOWERDOWN1_IN                (tied_to_ground_vec_i[1:0]),
         .TXPOWERDOWN0_IN                ({POWERDOWN_IN,POWERDOWN_IN}),
         .TXPOWERDOWN1_IN                (tied_to_ground_vec_i[1:0]),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE1),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE1),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE1),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE1),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi),
         .RXCHBONDI1_IN                 (chbondi_LANE1),
         .RXCHBONDO0_OUT                 (chbondo),
         .RXCHBONDO1_OUT                 (chbondo_LANE1),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE1),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE1 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE1),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE1),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE1),
         .RXDATAWIDTH0_IN                (tied_to_vcc_i),
         .RXDATAWIDTH1_IN                (tied_to_vcc_i),
         .RXRESET0_IN                   (RXRESET_IN ),
         .RXRESET1_IN                   (RXRESET_IN_LANE1),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXELECIDLE0_OUT                (rxelecidle0_i),
         .RXELECIDLE1_OUT                (rxelecidle1_i),
         .RXELECIDLERESET0_IN           (rxelecidlereset0_i),
         .RXELECIDLERESET1_IN          (rxelecidlereset1_i),
         .RXN0_IN                       (RX1N_IN),
         .RXN1_IN                       (RX1N_IN_LANE1),
         .RXP0_IN                       (RX1P_IN),
         .RXP1_IN                       (RX1P_IN_LANE1),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT,open_rxbufstatus_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE1,open_rxbufstatus_lane1_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT,open_txbufstatus_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE1,open_txbufstatus_lane1_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE1 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------
         .RXENSAMPLEALIGN0_IN           (tied_to_ground_i),
         .RXENSAMPLEALIGN1_IN           (tied_to_ground_i),

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE1),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTPRESET_IN                   (GTPRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT),
         .RESETDONE0_OUT                 (resetdone0_i),
         .RESETDONE1_OUT                 (resetdone1_i),
         .RXENELECIDLERESETB_IN         (rxenelecidleresetb_i),
         .TXENPMAPHASEALIGN_IN          (tied_to_ground_i),
         .TXPMASETPHASE_IN              (tied_to_ground_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE1),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN),
         .TXDATA1_IN                    (TXDATA_IN_LANE1),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE1),
         .TXRESET0_IN                   (TXRESET_IN ),
         .TXRESET1_IN                   (TXRESET_IN_LANE1),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT),
         .TXN1_OUT                       (TX1N_OUT_LANE1),
         .TXP0_OUT                       (TX1P_OUT),
         .TXP1_OUT                       (TX1P_OUT_LANE1),
			.TXDIFF									(TXDIFF),
			.TXPREEMP								(TXPREEMP)	
 );
 
 



   
//*************************************************************************************************            
//-----------------------------------Both GTPs in a Tile-------------------------------------------
//*************************************************************************************************
aur1_GTP_TILE #
    (
        //_______________________ Simulation-Only Attributes __________________
	.TILE_SIM_MODE                (SIM_MODE),
        .TILE_SIM_GTPRESET_SPEEDUP     (SIM_GTPRESET_SPEEDUP),
        .TILE_SIM_PLL_PERDIV2              (SIM_PLL_PERDIV2),
        .TILE_CHAN_BOND_LEVEL_0            (3'h1),
        .TILE_CHAN_BOND_LEVEL_1            (3'h0),
         .TILE_CHAN_BOND_MODE_0           (CHAN_BOND_MODE_0_LANE2),
         .TILE_CHAN_BOND_MODE_1           (CHAN_BOND_MODE_1_LANE3)
     ) 
GTP_TILE_INST_LANE1 (
         //---------------------- Loopback and Powerdown Ports ----------------------
         .LOOPBACK0_IN                  (LOOPBACK_IN),
         .LOOPBACK1_IN                  (LOOPBACK_IN),
         .RXPOWERDOWN0_IN                ({POWERDOWN_IN,POWERDOWN_IN}),
         .RXPOWERDOWN1_IN                (tied_to_ground_vec_i[1:0]),
         .TXPOWERDOWN0_IN                ({POWERDOWN_IN,POWERDOWN_IN}),
         .TXPOWERDOWN1_IN                (tied_to_ground_vec_i[1:0]),
         //--------------------- Receive Ports - 8b10b Decoder ----------------------
         .RXCHARISCOMMA0_OUT             (RXCHARISCOMMA_OUT_LANE2 ),
         .RXCHARISCOMMA1_OUT             (RXCHARISCOMMA_OUT_LANE3),
         .RXCHARISK0_OUT                 (RXCHARISK_OUT_LANE2),
         .RXCHARISK1_OUT                 (RXCHARISK_OUT_LANE3),
         .RXDISPERR0_OUT                 (RXDISPERR_OUT_LANE2),
         .RXDISPERR1_OUT                 (RXDISPERR_OUT_LANE3),
         .RXNOTINTABLE0_OUT              (RXNOTINTABLE_OUT_LANE2),
         .RXNOTINTABLE1_OUT              (RXNOTINTABLE_OUT_LANE3),
         //----------------- Receive Ports - Channel Bonding Ports ------------------
         .RXCHANBONDSEQ0_OUT             ( ),
         .RXCHANBONDSEQ1_OUT             ( ),
         .RXCHBONDI0_IN                 (chbondi_LANE2),
         .RXCHBONDI1_IN                 (chbondi_LANE3),
         .RXCHBONDO0_OUT                 (chbondo_LANE2),
         .RXCHBONDO1_OUT                 (chbondo_LANE3),
         .RXENCHANSYNC0_IN              (ENCHANSYNC_IN_LANE2),
         .RXENCHANSYNC1_IN              (ENCHANSYNC_IN_LANE3),
         //----------------- Receive Ports - Clock Correction Ports -----------------
         .RXCLKCORCNT0_OUT               (),
         .RXCLKCORCNT1_OUT               (),
         //------------- Receive Ports - Comma Detection and Alignment --------------
         .RXBYTEREALIGN0_OUT             (RXREALIGN_OUT_LANE2 ),
         .RXBYTEREALIGN1_OUT             (RXREALIGN_OUT_LANE3 ),
         .RXENMCOMMAALIGN0_IN           (ENMCOMMAALIGN_IN_LANE2),
         .RXENMCOMMAALIGN1_IN           (ENMCOMMAALIGN_IN_LANE3),
         .RXENPCOMMAALIGN0_IN           (ENPCOMMAALIGN_IN_LANE2),
         .RXENPCOMMAALIGN1_IN           (ENPCOMMAALIGN_IN_LANE3),
         //----------------- Receive Ports - RX Data Path interface -----------------
         .RXDATA0_OUT                    (RXDATA_OUT_LANE2),
         .RXDATA1_OUT                    (RXDATA_OUT_LANE3),
         .RXDATAWIDTH0_IN                (tied_to_vcc_i),
         .RXDATAWIDTH1_IN                (tied_to_vcc_i),
         .RXRESET0_IN                   (RXRESET_IN_LANE2 ),
         .RXRESET1_IN                   (RXRESET_IN_LANE3),
         .RXUSRCLK0_IN                  (RXUSRCLK_IN),
         .RXUSRCLK1_IN                  (RXUSRCLK_IN),
         .RXUSRCLK20_IN                 (RXUSRCLK2_IN),
         .RXUSRCLK21_IN                 (RXUSRCLK2_IN),
         //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
         .RXCDRRESET0_IN                (tied_to_ground_i),
         .RXCDRRESET1_IN                (tied_to_ground_i),
         .RXELECIDLE0_OUT                (rxelecidle0_lane1_i),
         .RXELECIDLE1_OUT                (rxelecidle1_lane1_i),
         .RXELECIDLERESET0_IN           (rxelecidlereset0_lane1_i),
         .RXELECIDLERESET1_IN          (rxelecidlereset1_lane1_i),
         .RXN0_IN                       (RX1N_IN_LANE2),
         .RXN1_IN                       (RX1N_IN_LANE3),
         .RXP0_IN                       (RX1P_IN_LANE2),
         .RXP1_IN                       (RX1P_IN_LANE3),
         //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
         .RXBUFRESET0_IN                (tied_to_ground_i),
         .RXBUFRESET1_IN                (tied_to_ground_i),
         .RXBUFSTATUS0_OUT               ({RXBUFERR_OUT_LANE2,open_rxbufstatus_lane2_i} ),
         .RXBUFSTATUS1_OUT               ({RXBUFERR_OUT_LANE3,open_rxbufstatus_lane3_i} ),
         .TXBUFSTATUS0_OUT               ({TXBUFERR_OUT_LANE2,open_txbufstatus_lane2_i} ),
         .TXBUFSTATUS1_OUT               ({TXBUFERR_OUT_LANE3,open_txbufstatus_lane3_i} ),
         .RXCHANISALIGNED0_OUT           (CHBONDDONE_OUT_LANE2),
         .RXCHANISALIGNED1_OUT           (CHBONDDONE_OUT_LANE3 ),
         .RXCHANREALIGN0_OUT             ( ),
         .RXCHANREALIGN1_OUT             ( ),
         //-------------------- Receive Ports - RX Oversampling ---------------------
         .RXENSAMPLEALIGN0_IN           (tied_to_ground_i),
         .RXENSAMPLEALIGN1_IN           (tied_to_ground_i),

         //--------------- Receive Ports - RX Polarity Control Ports ----------------
         .RXPOLARITY0_IN                (RXPOLARITY_IN_LANE2),
         .RXPOLARITY1_IN                (RXPOLARITY_IN_LANE3),
         //------------------- Shared Ports - Tile and PLL Ports --------------------
         .CLKIN_IN                      (REFCLK),

         .GTPRESET_IN                   (GTPRESET_IN),
         .PLLLKDET_OUT                   (plllkdet_lane1_i),
         .REFCLKOUT_OUT                  (REFCLKOUT_OUT_LANE1),
         .RESETDONE0_OUT                 (resetdone0_lane1_i),
         .RESETDONE1_OUT                 (resetdone1_lane1_i),
         .RXENELECIDLERESETB_IN         (rxenelecidleresetb_lane1_i),
         .TXENPMAPHASEALIGN_IN          (tied_to_ground_i),
         .TXPMASETPHASE_IN              (tied_to_ground_i),
         .TXCHARISK0_IN                 (TXCHARISK_IN_LANE2),
         .TXCHARISK1_IN                 (TXCHARISK_IN_LANE3),
         //---------------- Transmit Ports - TX Data Path interface -----------------
         .TXDATA0_IN                    (TXDATA_IN_LANE2),
         .TXDATA1_IN                    (TXDATA_IN_LANE3),
         .TXOUTCLK0_OUT                  (TXOUTCLK1_OUT_LANE2),
         .TXOUTCLK1_OUT                  (TXOUTCLK1_OUT_LANE3),
         .TXRESET0_IN                   (TXRESET_IN_LANE2 ),
         .TXRESET1_IN                   (TXRESET_IN_LANE3),
         .TXUSRCLK0_IN                  (TXUSRCLK_IN),
         .TXUSRCLK1_IN                  (TXUSRCLK_IN),
         .TXUSRCLK20_IN                 (TXUSRCLK2_IN),
         .TXUSRCLK21_IN                 (TXUSRCLK2_IN),
         //------------- Transmit Ports - TX Driver and OOB signalling --------------
         .TXN0_OUT                       (TX1N_OUT_LANE2),
         .TXN1_OUT                       (TX1N_OUT_LANE3),
         .TXP0_OUT                       (TX1P_OUT_LANE2),
         .TXP1_OUT                       (TX1P_OUT_LANE3),
			.TXDIFF									(TXDIFF),
			.TXPREEMP								(TXPREEMP)
 );
 
endmodule
